# Setup
title: Understanding the commands out of line
# tagline: Understanding the commands out of line
paginate: 1
permalink: pretty
url: https://clidetail.com
root: /
collections:
  manuals:
    output: true
  statistics_pipe:
    output: true
  statistics_double_pipe:
    output: true
  statistics_semicolon:
    output: true
  prerelease:
    output: true
    

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Custom vars
version: 3.0.0
